apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-node-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-node-api
  template:
    metadata:
      labels:
        app: secure-node-api
    spec:
      containers:
        - name: app
          image: shadoww717/secure-node-api:__IMAGE_TAG__
          ports:
            - containerPort: 3000
